apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app
  namespace: ync
  labels:
    app: shop-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
      - name: shop-app
        image: ync-app-shop:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: PUBLIC_URL
          value: "https://yn-corp.xyz/shop"
        - name: API_CONTACT_POINTS
          value: "10.43.6.1"
        - name: API_PORT
          value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: shop-app
  namespace: ync
spec:
  type: ClusterIP
  clusterIP: 10.43.6.2
  selector:
    app: shop-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
